"""Repositorio de canciones del catalogo."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from streaming_bot.domain.song import Song, SongRole
from streaming_bot.domain.value_objects import Country


@runtime_checkable
class ISongRepository(Protocol):
    async def get(self, song_id: str) -> Song | None: ...
    async def get_by_uri(self, uri: str) -> Song | None: ...
    async def get_by_isrc(self, isrc: str) -> Song | None: ...
    async def add(self, song: Song) -> None: ...
    async def update(self, song: Song) -> None: ...
    async def list_by_role(self, role: SongRole) -> list[Song]: ...
    async def list_targets_by_market(self, market: Country) -> list[Song]: ...
    async def list_pilot_eligible(self, *, max_songs: int = 60) -> list[Song]:
        """Devuelve zombies+low+mid no flagged en oct, listas para piloto."""
        ...

    async def count_active_targets(self) -> int: ...
