"""Listas realistas de fuentes instaladas por SO.

Sirven para dos propositos:
1. Inyectar `document.fonts` / matchMedia(font) consistente con el SO.
2. Generar un Font Hash (Pixelscan / Sannysoft / FingerprintJS) creible:
   un perfil "Windows" sin Segoe UI o un "macOS" sin Helvetica es bandera
   roja inmediata.

Listas extraidas y simplificadas a partir de los fingerprints publicos de
Sannysoft / Pixelscan 2025-Q4 (subset estable que NO depende de OEM).
"""

from __future__ import annotations

_FONTS_BY_OS: dict[str, tuple[str, ...]] = {
    "Windows": (
        "Arial",
        "Arial Black",
        "Bahnschrift",
        "Calibri",
        "Cambria",
        "Cambria Math",
        "Candara",
        "Comic Sans MS",
        "Consolas",
        "Constantia",
        "Corbel",
        "Courier New",
        "Ebrima",
        "Franklin Gothic Medium",
        "Gabriola",
        "Gadugi",
        "Georgia",
        "HoloLens MDL2 Assets",
        "Impact",
        "Ink Free",
        "Javanese Text",
        "Leelawadee UI",
        "Lucida Console",
        "Lucida Sans Unicode",
        "Malgun Gothic",
        "Marlett",
        "Microsoft Himalaya",
        "Microsoft JhengHei",
        "Microsoft New Tai Lue",
        "Microsoft PhagsPa",
        "Microsoft Sans Serif",
        "Microsoft Tai Le",
        "Microsoft YaHei",
        "Microsoft Yi Baiti",
        "MingLiU-ExtB",
        "MV Boli",
        "Myanmar Text",
        "Nirmala UI",
        "Palatino Linotype",
        "Segoe MDL2 Assets",
        "Segoe Print",
        "Segoe Script",
        "Segoe UI",
        "Segoe UI Emoji",
        "Segoe UI Historic",
        "Segoe UI Symbol",
        "SimSun",
        "Sitka",
        "Sylfaen",
        "Symbol",
        "Tahoma",
        "Times New Roman",
        "Trebuchet MS",
        "Verdana",
        "Webdings",
        "Wingdings",
        "Yu Gothic",
    ),
    "macOS": (
        "American Typewriter",
        "Andale Mono",
        "Arial",
        "Arial Black",
        "Arial Narrow",
        "Arial Rounded MT Bold",
        "Arial Unicode MS",
        "Avenir",
        "Avenir Next",
        "Avenir Next Condensed",
        "Baskerville",
        "Big Caslon",
        "Bodoni 72",
        "Bradley Hand",
        "Brush Script MT",
        "Chalkboard",
        "Chalkduster",
        "Charter",
        "Cochin",
        "Comic Sans MS",
        "Copperplate",
        "Courier",
        "Courier New",
        "Didot",
        "DIN Alternate",
        "DIN Condensed",
        "Futura",
        "Geneva",
        "Georgia",
        "Gill Sans",
        "Helvetica",
        "Helvetica Neue",
        "Herculanum",
        "Hoefler Text",
        "Impact",
        "Lucida Grande",
        "Luminari",
        "Marker Felt",
        "Menlo",
        "Microsoft Sans Serif",
        "Monaco",
        "Noteworthy",
        "Optima",
        "Palatino",
        "Papyrus",
        "Phosphate",
        "Rockwell",
        "San Francisco",
        "Savoye LET",
        "SignPainter",
        "Skia",
        "Snell Roundhand",
        "Tahoma",
        "Times",
        "Times New Roman",
        "Trattatello",
        "Trebuchet MS",
        "Verdana",
        "Zapfino",
    ),
    "Linux": (
        "Arimo",
        "Bitstream Charter",
        "Cantarell",
        "Comic Neue",
        "DejaVu Sans",
        "DejaVu Sans Mono",
        "DejaVu Serif",
        "Droid Sans",
        "Droid Sans Mono",
        "Droid Serif",
        "FreeMono",
        "FreeSans",
        "FreeSerif",
        "Inconsolata",
        "Liberation Mono",
        "Liberation Sans",
        "Liberation Sans Narrow",
        "Liberation Serif",
        "Lohit Bengali",
        "Lohit Devanagari",
        "Lohit Gujarati",
        "Lohit Punjabi",
        "Lohit Tamil",
        "Lohit Telugu",
        "Nimbus Mono L",
        "Nimbus Roman No9 L",
        "Nimbus Sans L",
        "Noto Color Emoji",
        "Noto Mono",
        "Noto Sans",
        "Noto Sans CJK JP",
        "Noto Sans CJK KR",
        "Noto Sans CJK SC",
        "Noto Sans CJK TC",
        "Noto Serif",
        "OpenSymbol",
        "Roboto",
        "Roboto Condensed",
        "Roboto Mono",
        "Source Code Pro",
        "Source Sans Pro",
        "Tlwg Mono",
        "Tlwg Typist",
        "Ubuntu",
        "Ubuntu Condensed",
        "Ubuntu Mono",
        "URW Bookman L",
        "URW Chancery L",
        "URW Gothic L",
        "URW Palladio L",
    ),
}


def fonts_for(os_family: str) -> tuple[str, ...]:
    """Devuelve la tupla de fuentes coherente con el SO.

    Para SO no reconocido cae en Linux (perfil mas neutro y conservador).
    """
    return _FONTS_BY_OS.get(os_family, _FONTS_BY_OS["Linux"])
